version: '3.9'

services:
  hotel-db:
    container_name: hotel-db
    image: 'postgres:16'
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel-db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5446:5432'
    volumes:
      - hotel-db-postgres-volume:/var/lib/postgresql/data


  hotel-x:
    container_name: hotel-x
    build:
      dockerfile: Dockerfile
    ports: 
        # external:internal
        - "8000:80"
    depends_on: 
      - hotel-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=hotel-db;Database=hotel-db;Username=postgres;Password=postgres
      - DOTNET_RUNNING_IN_CONTAINER=true

volumes:
  hotel-db-postgres-volume:
